# -*- coding: utf-8 -*-
"""Different Diet Group Environmental impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Vmtd0CQ0mM5aCcYiXFbuLiRXJGUWiVn
"""

import pandas as pd

# Load the data from the CSV file
file_path = 'sample_data/Results_21MAR2022_nokcaladjust.csv'
data = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to understand its structure
print(data.head())

# Display the column names to identify relevant fields
print(data.columns)

# Group the data by 'diet_group' and calculate average GHGs
ghg_by_diet = data.groupby('diet_group')['sd_ghgs'].mean()

# Display the results
print(ghg_by_diet)

# Normalize the GHG emissions data
ghg_normalized = (ghg_by_diet - ghg_by_diet.min()) / (ghg_by_diet.max() - ghg_by_diet.min())

# Display the normalized results
print(ghg_normalized)

# Group the data by 'diet_group' and calculate average GHGs
ghg_by_diet = data.groupby('diet_group')['sd_ghgs'].mean()

# Display the results
print(ghg_by_diet)

import pandas as pd

# Load the data
data = pd.read_csv('sample_data/Results_21MAR2022_nokcaladjust.csv')

# List of environmental impact metrics
metrics = ['sd_ghgs', 'sd_land', 'sd_eut', 'sd_bio', 'sd_watuse', 'sd_acid']

# Function to normalize data
def normalize(df):
    return (df - df.min()) / (df.max() - df.min())

# Calculate mean values for each metric and normalize
results = {}
for metric in metrics:
    grouped_data = data.groupby('diet_group')[metric].mean()
    normalized_data = normalize(grouped_data)
    results[metric] = normalized_data.round(2)

# Convert results dictionary to DataFrame for better visualization
results_df = pd.DataFrame(results)

# Display the results
print(results_df)

# Convert the DataFrame to a list of lists
results_list = results_df.reset_index().values.tolist()

# Display the list
print(results_list)